# python_opencv_shape_recognition

- 画像の写真を認識するプログラムをpythonでopenCVを使って試してみました
- 画像読み込みエラーに苦しめられましたが、おそらくicloud上に保存した画像を指定したために、ローカル環境にファイルの実体がないと認識され、パスが正しくてもエラーになったものと思われます。 `(-215:Assertion failed) !empty() in function`
- `ValueError: not enough values to unpack (expected 3, got 2)`のエラーが
